### PR TITLE
SWARM-1389: Add nexus-staging-maven-plugin to pluginManagement and updated jboss-parent.

### PR DESCRIPTION
**Pull request by gastaldi**
Motivation
----------
Remove warnings in build about nexus-staging-maven-plugin version not being defined

Modifications
-------------
Updated jboss-parent to 23 and added nexus-staging-maven-plugin to the pluginManagement section

Result
------
No errors when using this pom as the parent in core

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Can we not update jboss-parent?

I'd be worried that doing so introduces a lot of changes we're not expecting into downstream builds.

For now I'd prefer to stick with just the plugin version change in pluginManagement. I'm not even sure we should update the version on that either

**Comment by gastaldi** [comment]
Sure, done

**Comment by kenfinnigan** [comment]
staging plugins versions are still different.

without testing the whole way through the chain I'm loathe to make such a change right now

**Comment by gastaldi** [comment]
Ok, now it should be the same

**Review by kenfinnigan — APPROVED** [review]
Sorry for being pedantic, thanks!

**Comment by gastaldi** [comment]
No problem ;)

**Pull request merged**
